accounts/passwords/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^password/change/$', auth_views.PasswordChangeView.as_view(), name="password_change"),
    url(r'^password/change/done/$', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    url(r'^password/reset/$', auth_views.PasswordResetView.as_view(), name="password_reset"),
    url(r'^password/reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    url(r'^password/reset/complete/$', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

accounts/urls.py
from django.conf.urls import url

from products.views import UserProductHistoryView
from .views import (
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView
)

urlpatterns = [
    url(r'^$', AccountHomeView.as_view(), name='account-home'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

carts/urls.py
from django.conf.urls import url
from .views import (
    cart_home, cart_update,
    checkout_home,
    checkout_done_view
  )


urlpatterns = [
  url(r'^$', cart_home, name='home'),
  url(r'^checkout/$', checkout_home, name='checkout'),
  url(r'^update/$', cart_update, name='update'),
  url(r'^checkout/success/(?P<orderID>[\w\-]+)/$', checkout_done_view, name='success'),
]

eCommerce_Django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view,
    checkout_address_reuse_view
  )
from analytics.views import SalesView, SalesAjaxView
from accounts.views import LoginView, RegisterView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view, paypal_checkout_home
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import CollectionView
from .views import ProductListView, about_page, contact_page, update

from .sitemaps import global_maps, RobotsTxtView


urlpatterns = [
    url(r'^update_server/$', update, name='update'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^cart/create-paypal-transaction/$', paypal_checkout_home, name='paypal-checkout'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': global_maps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', RobotsTxtView.as_view()),

  ] + i18n_patterns(

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^$', ProductListView.as_view(), name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^collection/$', CollectionView.as_view(), name='collection'),
    url(r'^search/', include(('search.urls', 'eCommerce_Django'), namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),

    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include(('accounts.urls', 'eCommerce_Django'), namespace='accounts')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),

    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),

    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),

    url(r'^cart/', include(('carts.urls','eCommerce_Django'), namespace='cart')),

    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),

    url(r'^orders/', include(('orders.urls', 'eCommerce_Django'), namespace='orders')),

    url(r'^products/', include(('products.urls', 'eCommerce_Django'), namespace='products')),

    url(r'^admin/', admin.site.urls),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Olyalya Studio'
admin.site.index_title = 'Olyalya Studio'
admin.site.site_title = 'Olyalya Studio'

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext, gettext_lazy

from .models import EmailActivation, GuestEmail


User = get_user_model()


class ReactivateEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = EmailActivation.objects.email_exists(email)
        if not qs.exists():
            register_link = reverse('register')
            msg = gettext('This email does not exists, would you like to <a href="%(link)s">register</a>?') % { 'link': register_link }
            raise forms.ValidationError(mark_safe(msg))
        return email


class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label=gettext_lazy('Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=gettext_lazy('Password confirmation'), widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(gettext("Passwords don't match"))
        return password2

    def save(self, commit=True):
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserDetailChangeForm(forms.ModelForm):
    full_name = forms.CharField(label=gettext_lazy('Name'), required=False, widget=forms.TextInput(attrs={"class": 'form-control'}))

    class Meta:
        model = User
        fields = ['full_name']


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password', 'is_active', 'admin')

    def clean_password(self):
        return self.initial['password']


class GuestForm(forms.ModelForm):
    class Meta:
        model = GuestEmail
        fields = ['email']

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(GuestForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(GuestForm, self).save(commit=False)
        if commit:
            obj.save()
            request = self.request
            request.session['guest_email_id'] = obj.id
        return obj


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(label=gettext_lazy('Password'), widget=forms.PasswordInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        request = self.request
        data = self.cleaned_data
        email = data.get("email")
        password = data.get("password")
        qs = User.objects.filter(email=email)
        if qs.exists():
            not_active = qs.filter(is_active=False)
            if not_active.exists():
                link = reverse('accounts:resend-activation')
                reconfirm_msg = gettext('Go to <a href="%(resend_link)s">resend\n confirmation email</a>.') % { 'resend_link': link }
                confirm_email = EmailActivation.objects.filter(email=email)
                is_confirmable = confirm_email.confirmable().exists()
                if is_confirmable:
                    msg1 = gettext("Please check your email to confirm\n your account or ") + reconfirm_msg.lower()
                    raise forms.ValidationError(mark_safe(msg1))
                email_confirm_exists = EmailActivation.objects.email_exists(email).exists()
                if email_confirm_exists:
                    msg2 = gettext("Email not confirmed.") + reconfirm_msg
                    raise forms.ValidationError(mark_safe(msg2))
                if not is_confirmable and not email_confirm_exists:
                    raise forms.ValidationError(gettext("This user is inactive."))
        user = authenticate(request, username=email, password=password)
        if user is None:
            raise forms.ValidationError(gettext("Invalid credentials"))
        login(request, user)
        self.user = user
        return data


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label=gettext_lazy('Password'), widget=forms.PasswordInput)
    password2 = forms.CharField(label=gettext_lazy('Password confirmation'), widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('full_name', 'email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(gettext("Passwords don't match"))
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, FormView, DetailView, View, UpdateView
from django.utils.decorators import method_decorator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views.generic.edit import FormMixin
from django.utils.translation import gettext

from .forms import LoginForm, RegisterForm, GuestForm, ReactivateEmailForm, UserDetailChangeForm
from .models import GuestEmail, EmailActivation
from .signals import user_logged_in
from eCommerce_Django.mixins import NextUrlMixin, RequestFormAttachMixin


class AccountHomeView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/home.html'

    def get_object(self):
        return self.request.user


class AccountEmailActivateView(FormMixin, View):
    success_url = '/login/'
    form_class = ReactivateEmailForm
    key = None
    def get(self, request, key=None, *args, **kwargs):
        self.key = key
        if key is not None:
            qs = EmailActivation.objects.filter(key__iexact=key)
            confirm_qs = qs.confirmable()
            if confirm_qs.count() == 1:
                obj = confirm_qs.first()
                obj.activate()
                messages.success(request, gettext("Your email has been confirmed. Please login."))
                return redirect("login")
            else:
                activated_qs = qs.filter(activated=True)
                if activated_qs.exists():
                    reset_link = reverse("password_reset")
                    msg = gettext("Your email has already been confirmed. Do you need to <a href='%{link}s'>reset you password</a>?") % { 'link': reset_link }
                    messages.success(request, mark_safe(msg))
                    return redirect("login")
        context = {'form': self.get_form(), 'key': key}
        return render(request, 'registration/activation-error.html', context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        msg = gettext("Activation link sent, please, check your email.")
        request = self.request
        messages.success(request, msg)
        email = form.cleaned_data.get("email")
        obj = EmailActivation.objects.email_exists(email).first()
        user = obj.user
        new_activation = EmailActivation.objects.create(user=user, email=email)
        new_activation.send_activation()
        return super(AccountEmailActivateView, self).form_valid(form)

    def form_invalid(self, form):
        context = {'form': form, 'key': self.key}
        return render(self.request, 'registration/activation-error.html', context)


class GuestRegisterView(NextUrlMixin, RequestFormAttachMixin, CreateView):
    form_class = GuestForm
    default_next = '/register/'

    def get_success_url(self):
        return self.get_next_url()

    def form_invalid(self, form):
        return redirect(self.default_next)


class LoginView(NextUrlMixin, RequestFormAttachMixin, FormView):
    form_class = LoginForm
    success_url = '/'
    template_name = 'accounts/login.html'
    default_next = '/'

    def form_valid(self, form):
        next_path = self.get_next_url()
        return redirect(next_path)


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = '/login/'


class UserDetailUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserDetailChangeForm
    template_name = 'accounts/detail-update-view.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = gettext('Change Your Account Details')
        return context

    def get_success_url(self):
        return reverse('accounts:account-home')

accounts/templates/accounts/detail-update-view.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class='col-12 col-md-6 mx-auto base-canvas-cell-2'>
{% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
<form method='POST' action='{% if action_url %}{{ action_url }}{% else %}{% url "login" %}{% endif %}'> {% csrf_token %}
    {% if next_url %}
    <input type='hidden' name='next' value='{{ next_url }}' />
    {% endif %}
  {{ form.as_p }}
  <label for='email'>Email</label>
  <input type='text' id='email' class='form-control disabled' value='{{ request.user.email }}' disabled="disabled" />
    <span class='help-text'>{% trans "Cannot change email" %}
    </span>
    <br/>
  <button type='submit' class='btn btn-info my-3'>{% trans "Save" %}</button>
  <a href='{% url "password_change" %}'>{% trans "Change Password" %}</a>
</form>
</div>
{% endblock %}

accounts/templates/accounts/form.html
{% load i18n %}
<form method='POST' action="{% if action_url %}{{ action_url }}{% else %}{% url 'login' %}{% endif %}">
    {% csrf_token %}

    {% if next_url %}
        <input type="hidden" name="next" value="{{ next_url }}" />
    {% endif %}

    <div class="row">
        <div class="col">
            <label for="{{ form.email.id_for_label }}">Email:</label>
        </div>
        <div class="col">
            {{ form.email }}
        </div>
    </div>
    <div class="row form-errors">
        {{ form.email.errors }}
    </div>
    <div class="row">
        <div class="col">
            <label for="{{ form.password.id_for_label }}">{% trans "Password" %}:</label>
        </div>
        <div class="col">
            {{ form.password }}
        </div>
    </div>
    <div class="row form-errors">
        {{ form.password.errors }}
    </div>
    <hr>
    <div class="row">
        <div class="col-8 form-errors">
            {{ form.non_field_errors }}
        </div>
        <div class="col text-right">
            <button type='submit' class="btn btn-outline-warning">{% trans "Submit" %}</button>
        </div>
    </div>
</form>

accounts/templates/accounts/home.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class='row px-4'>

<div class='col-12'>
  <h1>{% trans "Account" %}</h1>
  <hr/>
</div>

<div class='col-12 col-sm-6 col-md-3 my-3'>
    <div class="card-home">
      <div class="card-home-body" style="background:#ff000050;">
        <h3 class="card-home-title">{% trans "Billing" %}</h3>
          <div class='list-group'>
            <a class='list-group-item' href='{% url "orders:list" %}'>{% trans "Orders" %}</a>
            <a class='list-group-item' href='{% url "billing-payment-method" %}'>{% trans "Payment Methods" %}</a>
            <a class='list-group-item' href='{% url "addresses" %}'>{% trans "Saved addresses" %}</a>
          </div>
      </div>
    </div>
</div>

<div class='col-12 col-sm-6 col-md-3 my-3'>
    <div class="card-home">
      <div class="card-home-body" style="background:#ffff0080;">
        <h3 class="card-home-title">{% trans "History" %}</h3>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "accounts:user-product-history" %}'>{% trans "Products" %}</a>
                <a class='list-group-item' href='{% url "collection" %}'>{% trans "Collection" %}</a>
                {% if user.staff %}
                  <a class='list-group-item' href='{% url "sales-analytics" %}'>{% trans "Statistics" %}</a>
                {% endif %}
            </div>
      </div>
    </div>
</div>

<div class='col-12 col-sm-6 col-md-3 my-3'>
    <div class="card-home">
      <div class="card-home-body" style="background:#00ff0080">
      <h3 class="card-home-title">{% trans "Support" %}</h3>
        <div class='list-group'>
          <a class='list-group-item' href='{% url "about" %}'>{% trans "About" %}</a>
          <a class='list-group-item' href='{% url "contact" %}'>{% trans "Contact" %}</a>
        </div>
      </div>
    </div>
</div>

<div class='col-12 col-sm-6 col-md-3 my-3'>
    <div class="card-home">
      <div class="card-home-body" style="background:#0000ff80;">
        <h3 class="card-home-title">{% trans "Account Details" %}</h3>
            <div class='list-group'>
                <a class='list-group-item' href='{% url "marketing-pref" %}'>{% trans "Email Marketing" %}</a>
                <a class='list-group-item' href='{% url "accounts:user-update" %}'>{% trans "Update Details" %}</a>
                <a class='list-group-item' href='{% url "password_change" %}'>{% trans "Change Password" %}</a>
            </div>
      </div>
    </div>
</div>

</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class="row justify-content-md-center">
    <div class="col col-sm-10 col-lg-8 col-xl-6 mx-4">
        <form class="base-canvas-cell" method='POST'> {% csrf_token %}
            <h1>{% trans "Login" %}</h1>
            <div class="row">
                <div class="col">
                    <label for="{{ form.email.id_for_label }}">Email:</label>
                </div>
                <div class="col">
                    {{ form.email }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.email.errors }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="{{ form.password.id_for_label }}">{% trans "Password" %}:</label>
                </div>
                <div class="col">
                    {{ form.password }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.password.errors }}
            </div>
            <hr>
            <div class="row">
                <div class="col-9 form-errors">
                    {{ form.non_field_errors }}
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-outline-info">{% trans "Sign in" %}</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class="row justify-content-md-center">
    <div class="col col-sm-10 col-lg-8 col-xl-6 mx-4">
        <form class="base-canvas-cell" method="POST"> {% csrf_token %}
            <h1>{% trans "Register" %}</h1>
            <div class="row">
                <div class="col">
                    <label for="{{ form.full_name.id_for_label }}">{% trans "Full name" %}:</label>
                </div>
                <div class="col">
                    {{ form.full_name }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.full_name.errors }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="{{ form.email.id_for_label }}">Email:</label>
                </div>
                <div class="col">
                    {{ form.email }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.email.errors }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="{{ form.password1.id_for_label }}">{% trans "Password" %}:</label>
                </div>
                <div class="col">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.password1.errors }}
            </div>
            <div class="row">
                <div class="col">
                    <label for="{{ form.password2.id_for_label }}">{% trans "Password confirmation" %}:</label>
                </div>
                <div class="col">
                    {{ form.password2 }}
                </div>
            </div>
            <div class="row form-errors">
                {{ form.password2.errors }}
            </div>
            <hr>
            <div class="row">
                <div class="col-8 form-errors">
                    {{ form.non_field_errors }}
                </div>
                <div class="col">
                    <button type='submit' class='btn btn-outline-info'>{% trans "Sign up" %}</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}