carts/urls.py
from django.conf.urls import url
from .views import (
    cart_home, cart_update,
    checkout_home,
    checkout_done_view
  )


urlpatterns = [
  url(r'^$', cart_home, name='home'),
  url(r'^checkout/$', checkout_home, name='checkout'),
  url(r'^update/$', cart_update, name='update'),
  url(r'^checkout/success/(?P<orderID>[\w\-]+)/$', checkout_done_view, name='success'),
]

addresses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy
from django.core.validators import RegexValidator

from billing.models import BillingProfile


ADDRESS_TYPES = (
    ('billing', gettext_lazy('Billing address')),
    ('shipping' , gettext_lazy('Shipping address'))
)


class Address(models.Model):
    billing_profile = models.ForeignKey(BillingProfile, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=120, null=True, blank=True, help_text=gettext_lazy('Shipping to? Who is it for?'))
    nickname = models.CharField(max_length=120, null=True, blank=True, help_text=gettext_lazy('Internal Reference Nickname'))
    address_type = models.CharField(max_length=120, choices=ADDRESS_TYPES)
    address_line_1 = models.CharField(max_length=120)
    address_line_2 = models.CharField(max_length=120, null=True, blank=True)
    country = models.CharField(max_length=2, default='RU', validators=[RegexValidator('^[A-Z]{2}$', gettext_lazy('Only uppercase letters and length has be 2'))])
    state = models.CharField(max_length=120)
    city = models.CharField(max_length=120)
    postal_code = models.CharField(max_length=120)

    def __str__(self):
        if self.nickname:
            return str(self.nickname)
        return str(self.address_line_1)

    def get_absolute_url(self):
        return reverse("address-update", kwargs={"pk": self.pk})

    def get_short_address(self):
        for_name = self.name
        if self.nickname:
            for_name = "{} | {},".format(self.nickname, for_name)
        return "{for_name} {line1}, {city}"\
            .format(
                for_name = for_name or "",
                line1 = self.address_line_1,
                city = self.city
            )

    def get_address(self):
        return '{for_name}\n{line1},\n{line2}\n{city},\n{state}, {postal},\n{country}'\
            .format(
                for_name = self.name or "",
                line1 = self.address_line_1,
                line2 = self.address_line_2 or "",
                city = self.city,
                state = self.state,
                postal = self.postal_code,
                country = self.country,
            )

addresses/forms.py
from django import forms
from django.utils.translation import gettext

from .models import Address
from .countries import countries_dict


class AddressForm(forms.ModelForm):
    def clean_country(self):
        country_code = self.cleaned_data.get('country')
        valid_code = False
        for country_union in countries_dict:
            if country_code == country_union['code']:
                valid_code = True
        if not valid_code:
            raise forms.ValidationError(gettext('Country code is not valid'))
        return country_code

    class Meta:
        model = Address
        fields = [
            'nickname',
            'name',
            # 'billing_profile',
            'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            'state',
            'postal_code'
        ]


class AddressCheckoutForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            'nickname',
            'name',
            # 'billing_profile',
            # 'address_type',
            'address_line_1',
            'address_line_2',
            'city',
            'country',
            'state',
            'postal_code'
        ]

addresses/views.py
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView, CreateView

from billing.models import BillingProfile
from .forms import AddressCheckoutForm, AddressForm
from .models import Address


class AddressListView(LoginRequiredMixin, ListView):
    template_name = 'addresses/list.html'

    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'

    def get_queryset(self):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        return Address.objects.filter(billing_profile=billing_profile)


class AddressCreateView(LoginRequiredMixin, CreateView):
    template_name = 'addresses/update.html'
    form_class = AddressForm
    success_url = '/addresses'

    def form_valid(self, form):
        request = self.request
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
        instance = form.save(commit=False)
        instance.billing_profile = billing_profile
        instance.save()
        return super(AddressCreateView, self).form_valid(form)


def checkout_address_create_view(request):
    form = AddressCheckoutForm(request.POST or None)
    context = { 'form': form }
    next_ = request.GET.get('next')
    next_post = request.POST.get('next')
    redirect_path = next_ or next_post or None

    if form.is_valid():
        instance = form.save(commit=False)
        billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

        if billing_profile is not None:
            address_type = request.POST.get('address_type', 'shipping')
            instance.billing_profile = billing_profile
            instance.address_type = address_type
            instance.save()
            request.session[address_type + '_address_id'] = instance.id
        else:
            print('Error redirect(cart:checkout)')
            return redirect('cart:checkout')

        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
    return redirect('cart:checkout')


def checkout_address_reuse_view(request):
    if request.user.is_authenticated:
        context = {}
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None

        if request.method == 'POST':
            shipping_address = request.POST.get('shipping_address', None)
            address_type = request.POST.get('address_type', 'shipping')
            billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

            if shipping_address is not None:
                qs = Address.objects.filter(billing_profile=billing_profile, id=shipping_address)

                if qs.exists():
                    request.session[address_type + '_address_id'] = shipping_address
                if is_safe_url(redirect_path, request.get_host()):
                    return redirect(redirect_path)
    return redirect('cart:checkout')

addresses/templates/addresses/form.html
{% load i18n %}

<form method="POST" action="{% if action_url %}{{ action_url }}{% else %}{% url 'login' %}{% endif %}">
    {% csrf_token %}

    {% if next_url %}
        <input type="hidden" name="next" value="{{ next_url }}" />
    {% endif %}

    {% if address_type %}
        <input type="hidden" name="address_type" value="{{ address_type }}" />
    {% endif %}

    <div class="row bank-canvas-cell-empty">
        <div class="col">
            <label for="{{ form.nickname.id_for_label }}">{% trans "Nickname" %} (Email):</label>
        </div>
        <div class="col-4">
            {{ form.nickname }}<br>
            <span class="helptext">({% trans "Internal Reference" %})</span>
        </div>
        <div class="col">
            <label for="{{ form.name.id_for_label }}">{% trans "Name" %}:</label>
        </div>
        <div class="col-4">
            {{ form.name }}<br>
            <span class="helptext">{% trans "Shipping to? Who is it for" %}?</span>
        </div>
    </div>
    <div class="row form-errors">
        <div class="col">
            {{ form.nickname.errors }}
        </div>
        <div class="col">
            {{ form.name.errors }}
        </div>
    </div>
    <div class="row bank-canvas-cell-empty">
        <div class="col">
            <label for="{{ form.address_line_1.id_for_label }}">{% trans "Street" %}:</label>
        </div>
        <div class="col-4">
            {{ form.address_line_1 }}
        </div>
        <div class="col">
            <label for="{{ form.address_line_2.id_for_label }}">{% trans "Apartment" %}:</label>
        </div>
        <div class="col-4">
            {{ form.address_line_2 }}
        </div>
    </div>
    <div class="row form-errors">
        {{ form.address_line_1.errors }}
        {{ form.address_line_2.errors }}
    </div>
    <div class="row bank-canvas-cell-empty">
        <div class="col">
            <label for="{{ form.city.id_for_label }}">{% trans "City" %}:</label>
        </div>
        <div class="col-4">
            {{ form.city }}
        </div>
        <div class="col">
            <label for="{{ form.country.id_for_label }}">{% trans "Country code" %}:</label>
        </div>
        <div class="col-4">
            {{ form.country }}
        </div>
    </div>
    <div class="row form-errors">
        <div class="col">
            {{ form.city.errors }}
        </div>
        <div class="col">
            {{ form.country.errors }}
        </div>
    </div>
    <div class="row bank-canvas-cell-empty">
        <div class="col">
            <label for="{{ form.state.id_for_label }}">{% trans "State" %}:</label>
        </div>
        <div class="col-4">
            {{ form.state }}
        </div>
        <div class="col">
            <label for="{{ form.postal_code.id_for_label }}">{% trans "Postal code" %}:</label>
        </div>
        <div class="col-4">
            {{ form.postal_code }}
        </div>
    </div>
    <div class="row form-errors">
        <div class="col">
            {{ form.state.errors }}
        </div>
        <div class="col">
            {{ form.postal_code.errors }}
        </div>
    </div>
    <hr>
    <div class="row bank-canvas-cell-empty">
        <div class="col-9 form-errors">
            {{ form.non_field_errors }}
        </div>
        <div class="col text-right">
            <button type="submit" class="btn btn-danger">{% trans "Submit" %}</button>
        </div>
    </div>
</form>

addresses/templates/addresses/list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class='row'>
    <div class='col'>
        <h1>{% trans "Saved addresses" %}{% if object_list.count > 1 %}{% trans "es" %}{% endif %} <small><a href='{% url "address-create" %}'>{% trans "Create New" %}</a></small></h1>
        <hr/>
    </div>
</div>
{% if object_list.exists %}
    <div class='row'>
        {% for obj in object_list %}
            <div class='col-12 col-md-3 my-3'>
                <div class="card">
                  <div class="card-body">
                     <h4 class="card-title">{{ obj }}</h4>
                     <small>{{ obj.get_address_type_display }}</small>
                     <br/>
                     <br/>
                     <h5>{% trans "Address" %}</h5>
                     {{ obj.get_address|linebreaks }}
                    <a href='{{ obj.get_absolute_url }}' class='btn btn-default'>{% trans "Edit" %}</a>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <a href='{% url "address-create" %}'>
        <div class="bank-canvas-cell-small-2">
            <h1>{% trans "No saved addresses" %}</h1>
        </div>
    </a>
{% endif %}
{% endblock %}

addresses/templates/addresses/prev_addresses.html
{% load i18n %}
{% if address_qs.exists %}
    <form method="POST" action="{% if action_url %}{{ action_url }}{% else %}{% url 'login' %}{% endif %}"> {% csrf_token %}

        {% if next_url %}
            <input type="hidden" name="next" value="{{ next_url }}" />
        {% endif %}

        {% if address_type %}
            <input type="hidden" name="address_type" value="{{ address_type }}" />
        {% endif %}

        {% for address in address_qs %}
            <label for="address={{ address.id }}">
                <div class="row bank-canvas-cell-small-2">
                    <div class="col">
                        <input id="address={{ address.id }}" type="radio" name="shipping_address" value="{{ address.id }}"/>
                        {{ address.get_short_address }}
                    </div>
                </div>
            </label>
            <br/>
        {% endfor %}
        <button type="submit" class="btn btn-danger">{% trans "Use Address" %}</button>
    </form>
{% endif %}

addresses/templates/addresses/update.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class='row'>
    <div class='col-10 mx-auto col-md-6'>
        <div class="bank-canvas-cell-2">
            {% if form.instance.address_line_1  %}
                <h3 class='my-5'>{% trans "Update Address" %}</h3>
            {% else %}
                <h3 class='my-5'>{% trans "Create Address" %}</h3>
            {% endif %}
            <hr>
            <form method="POST" action="">{% csrf_token %}
                <div class="row bank-canvas-cell-empty">
                    <div class="col">
                        <label for="{{ form.nickname.id_for_label }}">{% trans "Nickname" %} (Email):</label>
                    </div>
                    <div class="col-4">
                        {{ form.nickname }}<br>
                        <span class="helptext">({% trans "Internal Reference" %})</span>
                    </div>
                    <div class="col">
                        <label for="{{ form.name.id_for_label }}">{% trans "Name" %}:</label>
                    </div>
                    <div class="col-4">
                        {{ form.name }}<br>
                        <span class="helptext">{% trans "Shipping to? Who is it for" %}?</span>
                    </div>
                </div>
                <div class="row form-errors">
                    <div class="col">
                        {{ form.nickname.errors }}
                    </div>
                    <div class="col">
                        {{ form.name.errors }}
                    </div>
                </div>
                <div class="row bank-canvas-cell-empty">
                    <div class="col-2">
                        <label for="{{ form.address_type.id_for_label }}">{% trans "Type" %}: </label>
                    </div>
                    <div class="col">
                        <select name="address_type" class="form-control" required="" id="id_address_type">
                            <option value="">---------</option>
                            <option value="billing" selected="">{% trans "Billing address" %}</option>
                            <option value="shipping">{% trans "Shipping address" %}</option>
                        </select>
                    </div>
                </div>
                <div class="row bank-canvas-cell-empty">
                    <div class="col">
                        <label for="{{ form.address_line_1.id_for_label }}">{% trans "Address" %} 1:</label>
                    </div>
                    <div class="col-4">
                        {{ form.address_line_1 }}
                    </div>
                    <div class="col">
                        <label for="{{ form.address_line_2.id_for_label }}">{% trans "Address" %} 2:</label>
                    </div>
                    <div class="col-4">
                        {{ form.address_line_2 }}
                    </div>
                </div>
                <div class="row form-errors">
                    <div class="col">
                        {{ form.address_line_1.errors }}
                    </div>
                    <div class="col">
                        {{ form.address_line_2.errors }}
                    </div>
                </div>
                <div class="row bank-canvas-cell-empty">
                    <div class="col">
                        <label for="{{ form.city.id_for_label }}">{% trans "City" %}:</label>
                    </div>
                    <div class="col-4">
                        {{ form.city }}
                    </div>
                    <div class="col">
                        <label for="{{ form.country.id_for_label }}">{% trans "Country code" %}:</label>
                    </div>
                    <div class="col-4">
                        {{ form.country }}
                    </div>
                </div>
                <div class="row form-errors">
                    <div class="col">
                        {{ form.city.errors }}
                    </div>
                    <div class="col">
                        {{ form.country.errors }}
                    </div>
                </div>
                <div class="row bank-canvas-cell-empty">
                    <div class="col">
                        <label for="{{ form.state.id_for_label }}">{% trans "State" %}:</label>
                    </div>
                    <div class="col-4">
                        {{ form.state }}
                    </div>
                    <div class="col">
                        <label for="{{ form.postal_code.id_for_label }}">{% trans "Postal code" %}:</label>
                    </div>
                    <div class="col-4">
                        {{ form.postal_code }}
                    </div>
                </div>
                <div class="row form-errors">
                    <div class="col">
                        {{ form.state.errors }}
                    </div>
                    <div class="col">
                        {{ form.postal_code.errors }}
                    </div>
                </div>
                <hr>
                <div class="row bank-canvas-cell-empty">
                    <div class="col-8 form-errors">
                        {{ form.non_field_errors }}
                    </div>
                    <div class="col text-right">
                        <button type="submit" class="btn btn-danger">{% trans "Save Address" %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}