carts/urls.py
from django.conf.urls import url
from .views import (
    cart_home, cart_update,
    checkout_home,
    checkout_done_view
  )


urlpatterns = [
  url(r'^$', cart_home, name='home'),
  url(r'^checkout/$', checkout_home, name='checkout'),
  url(r'^update/$', cart_update, name='update'),
  url(r'^checkout/success/(?P<orderID>[\w\-]+)/$', checkout_done_view, name='success'),
]

eCommerce_Django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

from addresses.views import (
    AddressCreateView,
    AddressListView,
    AddressUpdateView,
    checkout_address_create_view,
    checkout_address_reuse_view
  )
from analytics.views import SalesView, SalesAjaxView
from accounts.views import LoginView, RegisterView
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view, paypal_checkout_home
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from orders.views import CollectionView
from .views import ProductListView, about_page, contact_page, update

from .sitemaps import global_maps, RobotsTxtView


urlpatterns = [
    url(r'^update_server/$', update, name='update'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^cart/create-paypal-transaction/$', paypal_checkout_home, name='paypal-checkout'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': global_maps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', RobotsTxtView.as_view()),

  ] + i18n_patterns(

    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^$', ProductListView.as_view(), name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^collection/$', CollectionView.as_view(), name='collection'),
    url(r'^search/', include(('search.urls', 'eCommerce_Django'), namespace='search')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),

    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include(('accounts.urls', 'eCommerce_Django'), namespace='accounts')),
    url(r'^accounts/', include('accounts.passwords.urls')),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),

    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),

    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),

    url(r'^cart/', include(('carts.urls','eCommerce_Django'), namespace='cart')),

    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),

    url(r'^orders/', include(('orders.urls', 'eCommerce_Django'), namespace='orders')),

    url(r'^products/', include(('products.urls', 'eCommerce_Django'), namespace='products')),

    url(r'^admin/', admin.site.urls),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Olyalya Studio'
admin.site.index_title = 'Olyalya Studio'
admin.site.site_title = 'Olyalya Studio'

products/urls.py
from django.conf.urls import url

from .views import (ProductListView, ProductDetailSlugView, ProductDownloadView)


urlpatterns = [
  url(r'^$', ProductListView.as_view(), name='list'),
  url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
  url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
]

chats/models.py
from django.db import models
from accounts.models import User
from products.models import Product


class Comment(models.Model):
    listing = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', null=True)
    msg = models.TextField(null=True)
    sender = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    send_time = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['send_time']

    def __str__(self):
        return 'Comment {} by {}'.format(self.msg, self.sender)

products/models.py
import os
import random
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from eCommerce_Django.utils import unique_slug_generator, get_filename


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1,4000000000)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return 'products/{new_filename}/{final_filename}'.format(new_filename=new_filename,final_filename=final_filename)


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def featured(self):
        return self.filter(featured=True, active=True)

    def search(self, query):
        lookups = (Q(title__icontains=query) | Q(description__icontains=query) | Q(price__icontains=query) | Q(tag__title__icontains=query))
        return self.filter(lookups).distinct()


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    delivery = models.BooleanField(default=True)
    views = models.IntegerField(default=0)

    objects = ProductManager()

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    @property
    def name(self):
        return self.title

    def get_downloads(self):
        qs = self.productfile_set.all()
        return qs


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)


def upload_product_file_loc(instance, filename):
    slug = instance.product.slug
    id_ = instance.id
    if id_ is None:
        Klass = instance.__class__
        qs = Klass.objects.all().order_by('-pk')
        if qs.exists():
            id_ = qs.first().id + 1
        else:
            id_ = 0
    if not slug:
        slug = unique_slug_generator(instance.product)
    location = "product/{slug}/{id}".format(slug=slug, id=id_)
    return location + filename


class ProductFile(models.Model):
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=120, default='', null=True, blank=True)
    description = models.TextField(default='', null=True, blank=True)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    file = models.FileField(upload_to=upload_product_file_loc, storage=FileSystemStorage(location=settings.PROTECTED_ROOT), blank=True)

    def __str__(self):
        return str(self.file)

    @property
    def display_name(self):
        if self.name:
            return self.name
        og_name = get_filename(self.file.name)
        return og_name

    def get_default_url(self):
        return self.product.get_absolute_url()

    def get_download_url(self):
        return reverse(
            "products:download",
            kwargs={
                "slug": self.product.slug,
                "pk": self.pk
            }
        )

products/views.py
import os
import json
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from django.http import Http404, HttpResponse, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from wsgiref.util import FileWrapper
from mimetypes import guess_type
from django.conf import settings
from django.core import serializers

from analytics.mixins import ObjectViewedMixin
from carts.models import Cart
from chats.models import Comment
from chats.forms import CommentForm
from .models import Product, ProductFile


class UserProductHistoryView(LoginRequiredMixin, ListView):
    template_name = "products/user-history.html"

    def get_context_data(self, *args, **kwargs):
        context = super(UserProductHistoryView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        views = request.user.objectviewed_set.by_model(Product, model_queryset=False)
        return views


class ProductListView(ListView):
    template_name = 'products/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


class ProductDetailSlugView(ObjectViewedMixin, DetailView):
    queryset = Product.objects.all()
    template_name = 'products/detail.html'

    def post(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        self.object = self.get_object()
        comment_form = CommentForm(data=request.POST)
        new_comment = None
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.listing = self.object
            new_comment.sender = request.user
            new_comment.save()
            context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
            return self.render_to_response(context=context)
        return JsonResponse({'error': 'Form is not valid'}, status=400)

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        slug = self.kwargs.get('slug')
        slides = ProductFile.objects.all().filter(product__slug=slug)
        context['slides'] = slides
        context['comments'] = ''
        context['comment_form'] = CommentForm()
        try:
            instance = Product.objects.get(slug=slug, active=True)
            context['comments'] = instance.comments.filter(active=True)
            instance.views = instance.views + 1
            context['views'] = instance.views
            instance.save()
        except Comment.DoesNotExist:
            raise Http404('Not found..')
        except:
            raise Http404('Indefinite')
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404('Not found..')
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404('Indefinite')
        return instance


class ProductFeaturedListView(ListView):
    template_name = 'products/list.html'

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductDownloadView(View):
    def get(self, request, *args, **kwargs):
        file_root = settings.PROTECTED_ROOT
        slug = kwargs.get('slug')
        pk = kwargs.get('pk')
        downloads_qs = ProductFile.objects.filter(pk=pk, product__slug=slug)
        if downloads_qs.count() != 1:
            raise Http404("Download not found")
        download_obj = downloads_qs.first()
        filepath = download_obj.file.path
        final_filepath = os.path.join(file_root, filepath)
        with open(final_filepath, 'rb') as f:
            wrapper = FileWrapper(f)
            mimetype = 'application/force-download'
            gussed_mimetype = guess_type(filepath)[0]
            if gussed_mimetype:
                mimetype = gussed_mimetype
            response = HttpResponse(wrapper, content_type=mimetype)
            response['Content-Disposition'] = "attachment;filename=%s" %(download_obj.name)
            response["X-SendFile"] = str(download_obj.name)
            return response
        return redirect(download_obj.get_default_url())

products/templates/products/card.html
{% load i18n %}

<div class="card px-4">
    {% if instance.image %}
        <a href="{{ instance.get_absolute_url }}">
            <img class="card-img-top" src="{{ instance.image.url }}" alt="{{ instance.title }} logo">
        </a>
    {% else %}
        <p class="text-center mt-2 mb-2">{% trans "Image not found :(" %}</p>
    {% endif %}
    <div class="row card-body">
        <div class="col-4 card-text">
            {% if complet == "1" %}
                <h5>{{ instance.title }}</h5>
                <p class="preview">{{ instance.description|safe|linebreaks|truncatewords:18 }}</p>
            {% else %}
                <h5>{{ instance.title }}</h5>
            {% endif %}
        </div>
        {% if complet == "1" %}
            <div class="col-5 card-button">
                <div class="row">
                    <div class="col-4 px-4 py-2">
                        <a href="{{ instance.get_absolute_url }}" class="btn btn-danger">{% trans "View" %}</a>
                    </div>
                    <div class="col-8 px-4 py-2 text-right">
                        {% include 'products/update-cart.html' with product=instance cart=cart %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="col-3 card-button">
                <div class="row">
                    <div class="col text-right">
                        <a href="{{ instance.get_absolute_url }}" class="btn btn-danger">{% trans "View" %}</a>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="col-3 pl-0 card-price text-right">
            <h2>{{ instance.price }} &#36;</h2>
        </div>
    </div>
</div>

products/templates/products/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% load humanize %}
{% load static %}

{% block extra_head_tags %}
<meta name="Description" content="Dress doll {{ object.title }} olyalya">
{% endblock extra_head_tags %}

    <div class="row ml-2 ml-md-0 detail-top-panel">
        <div class="col-8">
            <h4><b>{{ object.title }}</b></h4>
            <span class="badge badge-secondary">{{ object.timestamp|timesince }} {% trans "ago" %}</span>
            <span class="badge badge-secondary">{{ object.views }} views </span>
        </div>
        <div class="col">
            <div class="row detail-price-update">
                <div class="v-line">
                </div>
                <h2 class="text-center">
                  {{ object.price }} &#36;
                </h2>
                {% include 'products/update-cart.html' with product=object cart=cart %}
            </div>
        </div>
    </div>
    <hr/>
    <div class="row ml-2 ml-md-0 detail-content">
      <div class="col-4 detail-description preview">
        {{ object.description|linebreaks|safe }}
      </div>
      <div class="col-8">
        <div id="carouselAction" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselAction" data-slide-to="0" class="active"></li>
          {% for slide in slides %}
            <li data-target="#carouselAction" data-slide-to="{{ forloop.counter }}"></li>
            {{ forloop.counter1 }}
          {% endfor %}
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
            {% if object.image %}
                <img src="{{ object.image.url }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                  <h5>{{ object.title }}</h5>
                  <p class="preview">{{ object.description|safe }}</p>
                </div>
            {% else %}
              <p style="margin-left:50%; margin-top:50px;">{% trans "Image not found :(" %}</p>
            {% endif %}
            </div>
            {% for slide in slides %}
              <div class="carousel-item">
              {% if slide.image %}
                <img src="{{ slide.image.url }}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                  <h5>{{ slide.name }}</h5>
                  <p class="preview">{{ slide.description|safe }}</p>
                </div>
              {% else %}
                <p style="margin-left:50%; margin-top:50px;">{% trans "Image not found :(" %}</p>
              {% endif %}
              </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselAction" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans "Previous" %}</span>
          </a>
          <a class="carousel-control-next" href="#carouselAction" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans "Next" %}</span>
          </a>
        </div>
      </div>
    </div>
    <hr/>
    <div class="row detail-comments">
        <div class="col">
            <h6 class="text-right">{{ comments.count }} {% trans "comments" %}</h6>
            {% for comment in comments %}
                <hr/>
                <div class="row container-field">
                    <div class="col">
                        <h6><span class="badge badge-secondary">{{ comment.sender }}</span></h6>
                    </div>
                    <div class="col text-right">
                        <h6><em>{% trans "says" %}: {{ comment.send_time|naturaltime }}</em></h6>
                    </div>
                </div>
                <div class="container">
                    {{ comment.msg }}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row pt-4">
        <div class="col">
            {% if new_comment %}
                <div class="alert alert-success" role="alert">
                    {% trans "Your comment is awaiting moderation" %}
                </div>
            {% else %}
                <form method="POST" id="form_comments">
                    {% csrf_token %}
                    <div class="row d-flex justify-content-center">
                        <h2 class="text-center">{% trans "Leave a comment" %}</h2>
                        <div class="col-4"></div>
                        <button type="submit" class="btn btn-outline-info">{% trans "Submit" %}</button>
                    </div>
                    <br/>
                    <div class="row d-flex justify-content-center">
                        <label for="{{ form.msg.id_for_label }}"></label>
                        <textarea name="msg" cols="100" rows="10" required="" id="id_msg"></textarea>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock content %}

products/templates/products/list.html
{% extends "base.html" %}

{% block content %}

<div class="row text-center justify-content-center">
    {% for obj in object_list %}
        {% if forloop.counter0|divisibleby:2 %}
            </div><div class="row text-center justify-content-center">
        {% endif %}
        <div class="col-11 col-sm-8 col-lg-10 col-xl-8 my-3">
            {%  if object_list.count != 1 %}
                {% include 'products/card.html' with instance=obj complet="0" %}
            {% else %}
                {% include 'products/card.html' with instance=obj complet="1" %}
            {% endif %}
        </div>
    {% endfor %}

{% endblock %}

products/templates/products/update-cart.html
{% load i18n %}
<form class="form form-product-ajax" method="POST" action="{% url 'cart:update' %}"
    data-endpoint="{% url 'cart:update' %}" {% if request.user.is_authenticated %}data-user='abc'{% endif %}
>
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}" {% if product.delivery %} data-is-delivery='true'{% endif %} />

    <span class="submit-span">
        {% if product in cart.products.all %}
            <div class='btn-group'>
                <a class='btn btn-success' href='/cart/'>{% trans "In cart" %}</a>
                <button type="submit" class="btn btn-outline-danger">{% trans "Remove" %}?</button>
            </div>
        {% else %}
            <button type="submit" class="btn btn-success">{% trans "Add to cart" %}</button>
        {% endif %}
    </span>
</form>

products/templates/products/user-history.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

    <div class='row'>
        <div class='col'>
            <h1>{% trans "Product View History" %}</h1>
            <hr/>
        </div>
    </div>
{% if object_list.exists %}
    <div class="row text-center justify-content-center">
    {% for obj in object_list %}
        {% if forloop.counter0|divisibleby:2 %} </div><div class="row text-center justify-content-center" style="padding-left:2.5%;">{% endif %}
            <div class='col-11 col-sm-8 col-lg-10 col-xl-8 my-3'>
                {% trans "Viewed" %}: {{ forloop.counter }}
                {% include 'products/card.html' with instance=obj.content_object complet="0" %}
            </div>
    {% endfor %}
    </div>
{% else %}
    <a href='{% url "products:list" %}'>
        <div class="product-canvas-cell-small-2">
            <h1>{% trans "History missing" %}</h1>
        </div>
    </a>
{% endif %}
{% endblock %}